version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc/hc
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa/hc
      - HealthChecksUI__HealthChecks__2__Name=Web Shopping Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121/hc
      - HealthChecksUI__HealthChecks__3__Name=Mobile Shopping Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5120/hc
      - HealthChecksUI__HealthChecks__4__Name=Ordering HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102/hc
      - HealthChecksUI__HealthChecks__5__Name=Basket HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103/hc
      - HealthChecksUI__HealthChecks__6__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104/hc
      - HealthChecksUI__HealthChecks__7__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105/hc
      - HealthChecksUI__HealthChecks__8__Name=Marketing HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110/hc
      - HealthChecksUI__HealthChecks__9__Name=Locations HTTP Check
      - HealthChecksUI__HealthChecks__9__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5109/hc
      - HealthChecksUI__HealthChecks__10__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__10__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5108/hc
      - HealthChecksUI__HealthChecks__11__Name=Ordering SignalRHub HTTP Check
      - HealthChecksUI__HealthChecks__11__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5112/hc
      - HealthChecksUI__HealthChecks__12__Name=Ordering HTTP Background Check
      - HealthChecksUI__HealthChecks__12__Uri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5111/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - PurchaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - MarketingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5203
      - IdentityUrlHC=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5104:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - MarketingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5203
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrlHC=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5100:80"

